// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessNearMe.Migrations
{
    [DbContext(typeof(SupabaseDbContext))]
    [Migration("20250401105842_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessNearMe.Models.Country", b =>
                {
                    b.Property<long>("countryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("countryId"));

                    b.Property<string>("country_currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("country_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("countryId");

                    b.ToTable("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
